version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
              apt-get install curl
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin

      - run:
          name: Pull docker image
          command: |
            docker pull gableroux/unity3d
            docker build -t gableroux/unity3d:latest .