version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Pull docker image
          command: |
            docker pull gableroux/unity3d
            docker build -t gableroux/unity3d:latest .

      - run:
          name: Print the Current Time
          command: date